#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc config border_width 0
bspc config window_gap 5
bspc config top_padding 3.5
bspc config bottom_padding 5
bspc config left_padding 2
bspc config right_padding 2


bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

#start apps
sxhkd &
picom --corner-radius 13 --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
polybar &
fcitx &
eval $(dbus-launch) &

bspc rule -a Thunar state=floating
bspc rule -a lunarclient state=floating
bspc rule -a minecraft-launcher state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a Steam state=floating
bspc rule -a discord state=floating
bspc rule -a mpv state=fullscreen
bspc rule -a vlc state=floating
bspc rule -a mpv desktop="^5" follow=on
bspc rule -a spotify state=floating

xsetroot -cursor_name left_ptr
